// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_DoChoi.Repository;

#nullable disable

namespace Web_DoChoi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_DoChoi.Models.ChiNhanhModel", b =>
                {
                    b.Property<int>("PK_ChiNhanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ChiNhanh"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiThieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PK_ChiNhanh");

                    b.ToTable("ChiNhanhs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.ChiTietDonHangModel", b =>
                {
                    b.Property<int>("PK_ChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ChiTietDonHang"), 1L, 1);

                    b.Property<int>("FK_DoChoi")
                        .HasColumnType("int");

                    b.Property<int>("FK_DonHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSP")
                        .HasColumnType("int");

                    b.HasKey("PK_ChiTietDonHang");

                    b.HasIndex("FK_DoChoi");

                    b.HasIndex("FK_DonHang");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.ChiTietGioHangModel", b =>
                {
                    b.Property<int>("PK_ChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_ChiTietGioHang"), 1L, 1);

                    b.Property<int>("FK_DoChoi")
                        .HasColumnType("int");

                    b.Property<int>("FK_GioHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongSP")
                        .HasColumnType("int");

                    b.HasKey("PK_ChiTietGioHang");

                    b.HasIndex("FK_DoChoi");

                    b.HasIndex("FK_GioHang");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DanhGiaModel", b =>
                {
                    b.Property<int>("PK_DanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_DanhGia"), 1L, 1);

                    b.Property<int>("FK_DoChoi")
                        .HasColumnType("int");

                    b.Property<int>("FK_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("LoiDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSaoDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThem")
                        .HasColumnType("datetime2");

                    b.HasKey("PK_DanhGia");

                    b.HasIndex("FK_DoChoi");

                    b.HasIndex("FK_TaiKhoan");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DanhMucModel", b =>
                {
                    b.Property<int>("PK_DanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_DanhMuc"), 1L, 1);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("PK_DanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DiaChiModel", b =>
                {
                    b.Property<int>("PK_DiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_DiaChi"), 1L, 1);

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("SDTNhanHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_DiaChi");

                    b.HasIndex("FK_TaiKhoan");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DoChoiModel", b =>
                {
                    b.Property<int>("PK_DoChoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_DoChoi"), 1L, 1);

                    b.Property<string>("AnhDoChoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoTuoiGioiHan")
                        .HasColumnType("int");

                    b.Property<int>("FK_DanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("FK_NhaSanXuat")
                        .HasColumnType("int");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("GiaNhapHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhapHang")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotDanhGia")
                        .HasColumnType("int");

                    b.Property<float>("SoSao")
                        .HasColumnType("real");

                    b.Property<string>("TenDoChoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_DoChoi");

                    b.HasIndex("FK_DanhMuc");

                    b.HasIndex("FK_NhaSanXuat");

                    b.ToTable("DoChois");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DonHangModel", b =>
                {
                    b.Property<int>("PK_DonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_DonHang"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViVanChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("FK_TaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoiNhuan")
                        .HasColumnType("int");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianGiaoHangDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongGiaTri")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("PK_DonHang");

                    b.HasIndex("FK_MaKhuyenMai");

                    b.HasIndex("FK_TaiKhoan");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.GioHangModel", b =>
                {
                    b.Property<int>("PK_GioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_GioHang"), 1L, 1);

                    b.Property<int>("FK_TaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("PK_GioHang");

                    b.HasIndex("FK_TaiKhoan");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.LienHeModel", b =>
                {
                    b.Property<int>("PK_LienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_LienHe"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_LienHe");

                    b.ToTable("LienHes");
                });

            modelBuilder.Entity("Web_DoChoi.Models.MaKhuyenMaiModel", b =>
                {
                    b.Property<int>("PK_MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_MaKhuyenMai"), 1L, 1);

                    b.Property<int>("GiaTienApDung")
                        .HasColumnType("int");

                    b.Property<int>("GiaTienGiam")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMaGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("PK_MaKhuyenMai");

                    b.ToTable("MaKhuyenMais");
                });

            modelBuilder.Entity("Web_DoChoi.Models.NhaSanXuatModel", b =>
                {
                    b.Property<int>("PK_NSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_NSX"), 1L, 1);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("PK_NSX");

                    b.ToTable("NhaSanXuats");
                });

            modelBuilder.Entity("Web_DoChoi.Models.OrderInfoModel", b =>
                {
                    b.Property<int>("PK_Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_Order"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("FK_DonHang")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderInfor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("PK_Order");

                    b.ToTable("OrderInfos");
                });

            modelBuilder.Entity("Web_DoChoi.Models.SlideModel", b =>
                {
                    b.Property<int>("PK_Slide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_Slide"), 1L, 1);

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Slide");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("Web_DoChoi.Models.TaiKhoanModel", b =>
                {
                    b.Property<int>("PK_TaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_TaiKhoan"), 1L, 1);

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_TaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("Web_DoChoi.Models.TinTucModel", b =>
                {
                    b.Property<int>("PK_TinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_TinTuc"), 1L, 1);

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTinTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("PK_TinTuc");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("Web_DoChoi.Models.ChiTietDonHangModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.DoChoiModel", "DoChoi")
                        .WithMany()
                        .HasForeignKey("FK_DoChoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_DoChoi.Models.DonHangModel", "DonHang")
                        .WithMany()
                        .HasForeignKey("FK_DonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoChoi");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("Web_DoChoi.Models.ChiTietGioHangModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.DoChoiModel", "DoChoi")
                        .WithMany()
                        .HasForeignKey("FK_DoChoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_DoChoi.Models.GioHangModel", "GioHang")
                        .WithMany()
                        .HasForeignKey("FK_GioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoChoi");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DanhGiaModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.DoChoiModel", "DoChoi")
                        .WithMany()
                        .HasForeignKey("FK_DoChoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_DoChoi.Models.TaiKhoanModel", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("FK_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoChoi");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DiaChiModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.TaiKhoanModel", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("FK_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DoChoiModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.DanhMucModel", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("FK_DanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_DoChoi.Models.NhaSanXuatModel", "NhaSanXuat")
                        .WithMany()
                        .HasForeignKey("FK_NhaSanXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaSanXuat");
                });

            modelBuilder.Entity("Web_DoChoi.Models.DonHangModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.MaKhuyenMaiModel", "MaKhuyenMai")
                        .WithMany()
                        .HasForeignKey("FK_MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_DoChoi.Models.TaiKhoanModel", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("FK_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaKhuyenMai");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Web_DoChoi.Models.GioHangModel", b =>
                {
                    b.HasOne("Web_DoChoi.Models.TaiKhoanModel", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("FK_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
